# Number of days of inactivity before an issue becomes stale
daysUntilStale: 365
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 14
# Issues with these labels will never be considered stale
exemptLabels:
  - pinned
  - security
  - blocking
  - bug
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has not had any activity for over one year, so it has been marked as stale. 
  It will be closed in 14 days if no further activity occurs.
  If you would like to keep this issue open, please comment giving an update and confirming its relevance.
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
